### ISSUE TITLE
too many sql connections sleep

### ISSUE THREAD

**Issue by imranariffin** [hooligram/hooligram-server#69]
Currently a single user will create multiple sql connections and let them idle while sql service (JawsDB) provider limit connections to only 10.

**Comment by imranariffin** [comment]
Also set timeout, max connections etc

**Comment by cglotr** [comment]
@imranariffin Interesting find:
https://golang.org/pkg/database/sql/#Rows
*Close closes the Rows, preventing further enumeration. **If Next is called and returns false and there are no further result sets, the Rows are closed automatically** and it will suffice to check the result of Err. Close is idempotent and does not affect the result of Err.*

**Comment by cglotr** [comment]
> Also set timeout, max connections etc

I just thought something about this. I think we shouldn't do this and wait for something bad to happen before doing this. This is because closing rows should fix the issue and we don't really know if there are processes that want to sleep (basically we don't know the side effect of forcing no process to sleep)

**Comment by cglotr** [comment]
@imranariffin I am doing this since this is blocking for client development. I prefer the client to be connected to Heroku to catch problems if they arise.
